// <auto-generated />
using EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFramework.Migrations
{
    [DbContext(typeof(SqlLiteDbContext))]
    [Migration("20230201135708_testMigration")]
    partial class testMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("DTO_EF.ChampionEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Champions");

                    b.HasData(
                        new
                        {
                            Name = "Akali",
                            Bio = "",
                            Class = "Assassin",
                            Icon = ""
                        },
                        new
                        {
                            Name = "Aatrox",
                            Bio = "",
                            Class = "Fighter",
                            Icon = ""
                        },
                        new
                        {
                            Name = "Ahri",
                            Bio = "",
                            Class = "Mage",
                            Icon = ""
                        },
                        new
                        {
                            Name = "Akshan",
                            Bio = "",
                            Class = "Marksman",
                            Icon = ""
                        },
                        new
                        {
                            Name = "Bard",
                            Bio = "",
                            Class = "Support",
                            Icon = ""
                        },
                        new
                        {
                            Name = "Alistar",
                            Bio = "",
                            Class = "Tank",
                            Icon = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
