// <auto-generated />
using EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFramework.Migrations
{
    [DbContext(typeof(SqlLiteDbContextWithStub))]
    partial class SqlLiteDbContextWithStubModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("DTO_EF.ChampionEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Champions");

                    b.HasData(
                        new
                        {
                            Name = "Akali",
                            Bio = "",
                            Class = "Assassin",
                            Icon = "",
                            Image = ""
                        },
                        new
                        {
                            Name = "Aatrox",
                            Bio = "",
                            Class = "Fighter",
                            Icon = "",
                            Image = ""
                        });
                });

            modelBuilder.Entity("DTO_EF.RuneEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Familly")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Runes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            Familly = "Precision",
                            Image = "",
                            Name = "Conqueror"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            Familly = "Precision",
                            Image = "",
                            Name = "Legend: Alacrity"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            Familly = "Domination",
                            Image = "",
                            Name = "last stand 2"
                        });
                });

            modelBuilder.Entity("DTO_EF.SkinEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChampionForeignKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ChampionForeignKey");

                    b.ToTable("Skins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChampionForeignKey = "Akali",
                            Description = "",
                            Icon = "",
                            Image = "",
                            Name = "Stinger",
                            Price = 0f
                        },
                        new
                        {
                            Id = 2,
                            ChampionForeignKey = "Akali",
                            Description = "",
                            Icon = "",
                            Image = "",
                            Name = "Infernal",
                            Price = 0f
                        },
                        new
                        {
                            Id = 3,
                            ChampionForeignKey = "Akali",
                            Description = "",
                            Icon = "",
                            Image = "",
                            Name = "All-Star",
                            Price = 0f
                        },
                        new
                        {
                            Id = 4,
                            ChampionForeignKey = "Aatrox",
                            Description = "",
                            Icon = "",
                            Image = "",
                            Name = "Justicar",
                            Price = 0f
                        },
                        new
                        {
                            Id = 5,
                            ChampionForeignKey = "Aatrox",
                            Description = "",
                            Icon = "",
                            Image = "",
                            Name = "Mecha",
                            Price = 0f
                        },
                        new
                        {
                            Id = 6,
                            ChampionForeignKey = "Aatrox",
                            Description = "",
                            Icon = "",
                            Image = "",
                            Name = "Sea Hunter",
                            Price = 0f
                        });
                });

            modelBuilder.Entity("DTO_EF.SkinEntity", b =>
                {
                    b.HasOne("DTO_EF.ChampionEntity", "Champion")
                        .WithMany("Skins")
                        .HasForeignKey("ChampionForeignKey");

                    b.Navigation("Champion");
                });

            modelBuilder.Entity("DTO_EF.ChampionEntity", b =>
                {
                    b.Navigation("Skins");
                });
#pragma warning restore 612, 618
        }
    }
}
